specification/archSpec/base/processing-controlled-attribute-values.dita, specification/errata-01/grammar-files.dita, specification/errata-01/written-spec.dita
* Change to "processing controlled values" topic
* Documenting that change in the errata document
* Documenting #12 in errata document
=> Update errata doc (including #12)

specification/dita-13-key-definitions-cover-pages.ditamap, specification/resources/oasis-errata-cover-all-inclusive.dita, specification/resources/oasis-errata-cover-base.dita, specification/resources/oasis-errata-cover-overview.dita, specification/resources/oasis-errata-cover-tech-content.dita, specification/resources/oasis-errata-cover.dita
Initial pass at updating the keys and topics for the cover pages
=> Update cover page links and OASIS keys

specification/dita-13-key-definitions-cover-pages.ditamap
Removed orphan key; improved comments
=> Cleanup of cover page key definitions

specification/errata-01/acknowledgments.dita, specification/errata-01/revision-history.dita
* Added Roberta Anderson, Bob Thomas, and Eliot Kimber to the Acknowledgments topic
* Added 09 May 2017 change to the Revision history topic
=> Update Acknowledgments and Revision history topics

specification/dita-1.3-errata01-specification-base.ditamap, specification/dita-1.3-errata01-specification-learningTraining.ditamap, specification/dita-1.3-errata01-specification-overview.ditamap, specification/dita-1.3-errata01-specification-technicalContent.ditamap, specification/dita-1.3-errata01-specification.ditamap, specification/dita-13-key-definitions-cover-pages.ditamap, specification/resources/DITA1.3-spec-base.ditaval, specification/resources/DITA1.3-spec-errata.ditaval, specification/resources/DITA1.3-spec-learningTraining.ditaval, specification/resources/DITA1.3-spec-overview.ditaval, specification/resources/DITA1.3-spec-technicalContent.ditaval, specification/resources/oasis-errata-cover-all-inclusive.dita, specification/resources/oasis-errata-cover-base.dita, specification/resources/oasis-errata-cover-overview.dita, specification/resources/oasis-errata-cover-tech-content.dita, specification/resources/oasis-errata-cover.dita
* Updated DITAVAL for errata
* Updated resource files to use keyref'd content for titles in "Additional artifacts"
* Updated titles and copyright info in master maps for the parts
* Updated previous links in key definition maps for cover pages
=> Update errata source

specification/resources/oasis-errata-cover-all-inclusive.dita, specification/resources/oasis-errata-cover-overview.dita, specification/resources/oasis-errata-cover.dita
Corrections based on Eliot's review of cover page links
=> Correct links

specification/errata-01/written-spec.dita, specification/langRef/technicalContent/equation-block.dita
Per Robert Anderson's e-mail to TC list on 6 June 2017
=> Updated Inheritance for <equation-block> & edited errata 02 document

specification/errata-01/written-spec.dita, specification/langRef/technicalContent/equation-block.dita
=> Corrected markup error in errata document

specification/archSpec/technicalContent/dita-task-topic.dita
=> Correcting error in example

specification/archSpec/base/usage-of-conditional-processing-attributes.dita, specification/dita-13-key-definitions-common-metadata.ditamap, specification/errata-01/written-spec.dita
Updates to common metadata map; errata fixes; update errata document
=> Errata fixes

specification/dita-1.3-errata01-specification.ditamap, specification/dita-13-key-definitions-common-metadata.ditamap
Updates to source for new style sheets
=> Changes to @outputclass and key values

specification/langRef/base/anchorref.dita, specification/langRef/base/keydef.dita, specification/langRef/base/mapref.dita, specification/langRef/base/topicgroup.dita, specification/langRef/base/topichead.dita, specification/langRef/base/topicset.dita, specification/langRef/base/topicsetref.dita, specification/langRef/base/ux-window.dita, specification/langRef/containers/mapgroup-d.dita
Changes to map group element topics
=> Updates to implement new structure

specification/langRef/base-elements.ditamap, specification/langRef/delay-conref-elements.ditamap, specification/langRef/indexing-elements.ditamap, specification/langRef/prolog-elements.ditamap
=> Submaps for metadata elements

specification/langRef/base/subjectCell.dita, specification/langRef/base/subjectref.dita, specification/langRef/base/topicCell.dita, specification/langRef/base/topicSubjectHeader.dita, specification/langRef/base/topicSubjectRow.dita, specification/langRef/base/topicSubjectTable.dita, specification/langRef/base/topicapply.dita, specification/langRef/base/topicsubject.dita, specification/langRef/classification-domain-elements.ditamap
Restructure topics; put them in alphabetical order
=> Changes to classification domain element topics and map

specification/errata-01/written-spec.dita, specification/langRef/base/required-cleanup.dita, specification/langRef/base/subjectHead.dita
Fixes to subjectHead and required-cleanup elements
=> Errata 02 fixes on 31 August

specification/langRef/base/attributedef.dita, specification/langRef/base/subjectdef.dita
Changes (not complete) based on call with R Anderson
=> Changes based on call with Robert Anderson, 31 August 2017

specification/errata-01/written-spec.dita, specification/langRef/base/required-cleanup.dita
Errata 02 changes to the required-cleanup topic
=> Errata fix to the <required-cleanup> topic

specification/langRef/base/defaultSubject.dita, specification/langRef/base/elementdef.dita, specification/langRef/base/enumerationdef.dita, specification/langRef/base/hasInstance.dita, specification/langRef/base/hasKind.dita, specification/langRef/base/hasNarrower.dita, specification/langRef/base/hasPart.dita, specification/langRef/base/hasRelated.dita, specification/langRef/base/relatedSubjects.dita, specification/langRef/base/schemeref.dita, specification/langRef/base/subjectHead.dita, specification/langRef/base/subjectHeadMeta.dita, specification/langRef/base/subjectRel.dita, specification/langRef/base/subjectRelHeader.dita, specification/langRef/base/subjectRelTable.dita, specification/langRef/base/subjectRole.dita, specification/langRef/base/subjectScheme.dita
Updating specialization hierarchy section for subjectScheme elements
=> Updating specialization hierarchy section

specification/archSpec/base/classification-maps.dita, specification/langRef/base/subjectdef.dita, specification/langRef/base/subjectref.dita, specification/langRef/base/topicCell.dita, specification/langRef/base/topicSubjectHeader.dita, specification/langRef/base/topicSubjectRow.dita, specification/langRef/base/topicSubjectTable.dita, specification/langRef/base/topicsubject.dita, specification/langRef/containers/classify-d.dita
Edits to classification domain topics
=> Edits to classification domain topics

specification/archSpec/base/specialization-overview.dita, specification/errata-01/written-spec.dita
Correct typo in "Overview of specialization" topic
=> Correct typo in "Overview of specialization" topic

specification/errata-01/written-spec.dita, specification/langRef/base/created.dita
Fix code example in created topic; add value for modified attr
=> Fix code example in created topic

specification/resources/oasis-notices.dita
Changed 2016 to 2017 in Notices topic
=> Changed 2016 to 2017 in Notices topic

specification/errata-01/grammar-files.dita, specification/errata-01/written-spec.dita, specification/langRef/base/image.dita
=> Add image/@format as discussed at recent TC meeting

doctypes/rng/subjectScheme/rng/subjectSchemeMod.rng, doctypes/rng/technicalContent/rng/referenceMod.rng, doctypes/rng/technicalContent/rng/taskMod.rng
Based on: https://lists.oasis-open.org/archives/dita/201710/msg00033.html
And errata approved: https://lists.oasis-open.org/archives/dita/201711/msg00009.html
=> Replaced declarations of domains att in modules with reference to domains-att

specification/dita-13-key-definitions-cover-pages.ditamap, specification/errata-01/revision-history.dita, specification/introduction/formatting-conventions-in-errata.dita
Updating date in errata map; formatting conventions in errata document
=> Updates for working draft 01

specification/dita-1.3-errata01-specification.ditamap, specification/errata-01/change-list.dita, specification/errata-01/content-models.dita, specification/errata-01/grammar-files.dita, specification/errata-01/written-spec.dita, specification/errata-02/introduction.dita
Added errata 01 content; modified acknowledgments and introduction
=> Second round of IA changes

specification/errata-02/comment-resolution-log.dita
To reflect our current usage of GitHub rather than SVN
=> Update comment-resolution log

specification/DITA-1.3-specification-subjectScheme.ditamap, specification/archSpec/base/specialization-overview.dita, specification/archSpec/technicalContent/dita-task-topic.dita, specification/dita-1.3-errata01-specification-learningTraining.ditamap, specification/errata-02/acknowledgments.dita, specification/errata-02/revision-history.dita, specification/errata-02/written-spec.dita, specification/langRef/attributes/simpletableAttributes.dita, specification/langRef/base/indexterm.dita, specification/resources/oasis-notices.dita
=> DITAweb review

specification/dita-13-key-definitions-cover-pages.ditamap
=> Update key for "specification-level"

specification/dita-1.3-errata-specification-base.ditamap, specification/dita-1.3-errata-specification-learningTraining.ditamap, specification/dita-1.3-errata-specification-overview.ditamap, specification/dita-1.3-errata-specification-technicalContent.ditamap, specification/dita-13-key-definitions-cover-pages.ditamap, specification/resources/oasis-errata-cover-all-inclusive.dita, specification/resources/oasis-errata-cover-base.dita, specification/resources/oasis-errata-cover-overview.dita, specification/resources/oasis-errata-cover-tech-content.dita
Changes to keys, cover page content, and map subtitles
=> Corrections based on feedback from Paul Knight

doctypes/rng/base/rng/commonElementsMod.rng, doctypes/rng/base/rng/mapGroupDomain.rng, doctypes/rng/base/rng/mapMod.rng, doctypes/rng/base/rng/topicMod.rng, specification/archSpec/base/relax-ng-coding-element-types.dita
Implementing changes outlined in stage three proposal for issue #36 Remove deprecated items
=> Changes to RNG files for issue#36: Remove deprecated items

doctypes/dtd/base/dtd/commonElements.mod, doctypes/dtd/base/dtd/map.mod, doctypes/dtd/base/dtd/mapGroup.mod, doctypes/dtd/base/dtd/topic.mod, specification/archSpec/base/dtd-coding-element-types.dita
Implemented changes to DTDs for issue #36 Remove deprecated items
=> Changes to DTD files for issue#36: Remove deprecated items

specification/langRef/base/relcolspec.dita, specification/langRef/base/reltable.dita
2nd round of changes to written spec topics: reltable and relcolspec
=> #36: Remove deprecated items

doctypes/dtd/base/dtd/map.mod, doctypes/dtd/subjectScheme/dtd/subjectScheme.mod, doctypes/rng/base/rng/ditavalrefDomain.rng, doctypes/rng/base/rng/mapGroupDomain.rng, doctypes/rng/subjectScheme/rng/classifyDomain.rng, doctypes/rng/subjectScheme/rng/subjectSchemeMod.rng
Remove @navtitle; remove @outputclass from elements with univ-atts
=> Remove @navtitle and duplicate @outputclass

specification/common/conref-cover-pages.dita, specification/dita-13-key-definitions-cover-pages.ditamap
Add keys; rework xrefs to use keys
=> Correct links in Status section

specification/dita-13-key-definitions-common-metadata.ditamap, specification/dita-13-key-definitions-cover-pages.ditamap
Additional comments for key definitions
=> Comments for key definitions

specification/acknowledgments/acknowledgments.dita, specification/archSpec/archSpec-base.dita, specification/archSpec/archSpec-base.ditamap, specification/archSpec/base/addressing.ditamap, specification/archSpec/base/branch-filtering.ditamap, specification/archSpec/base/conditonal-processing.ditamap, specification/archSpec/base/configuration.ditamap, specification/archSpec/base/ditamarkup.ditamap, specification/archSpec/base/maps.ditamap, specification/archSpec/base/metadata.ditamap, specification/archSpec/base/processing.ditamap, specification/archSpec/base/specialization-and-custom-doctypes.ditamap, specification/archSpec/base/topics.ditamap, specification/archSpec/base/translation-and-localization.ditamap, specification/common/conref-examples.dita, specification/dita-2.0-specification.ditamap, specification/introduction/about-the-dita-specification-base.dita, specification/introduction/introduction.ditamap, specification/langRef/base/elementdef.dita, specification/langRef/base/enumerationdef.dita, specification/langRef/langRef-base.dita
Basic cleanup: Removing navtitles etc
=> Basic cleanup: Removing navtitles etc

specification/langRef/attributes/ditaref-attributes.ditamap, specification/langRef/base-elements.ditamap, specification/langRef/basic-map-elements.ditamap, specification/langRef/basic-topic-elements.ditamap, specification/langRef/body-elements.ditamap, specification/langRef/classification-domain-elements.ditamap, specification/langRef/delay-conref-elements.ditamap, specification/langRef/ditaref-ditaval.ditamap, specification/langRef/ditavalref-elements.ditamap, specification/langRef/hazard-statement-elements.ditamap, specification/langRef/highlighting-elements.ditamap, specification/langRef/indexing-elements.ditamap, specification/langRef/map-group-elements.ditamap, specification/langRef/prolog-elements.ditamap, specification/langRef/related-links-elements.ditamap, specification/langRef/specialization-elements.ditamap, specification/langRef/subjectScheme-elements.ditamap, specification/langRef/table-elements.ditamap, specification/langRef/utilities-elements.ditamap
Remove navtitle attributes from maps
=> Remove navtitle attributes from maps

specification/dita-1.3-errata-specification-base.ditamap, specification/dita-13-key-definitions-common-metadata.ditamap, specification/dita-13-key-definitions-cover-pages.ditamap, specification/errata-02/revision-history.dita, specification/resources/oasis-errata-cover-all-inclusive.dita, specification/resources/oasis-errata-cover-base.dita, specification/resources/oasis-errata-cover-overview.dita, specification/resources/oasis-errata-cover-tech-content.dita, specification/resources/oasis-errata-cover.dita
Update topics and metadata for "os" stage
=> Final errata 02 build

specification/langRef/base/consequence.dita, specification/langRef/base/hazardstatement.dita, specification/langRef/base/hazardsymbol.dita, specification/langRef/base/howtoavoid.dita, specification/langRef/base/messagepanel.dita, specification/langRef/base/typeofhazard.dita, specification/langRef/containers/hazard-d.dita
Updates to comply with DITA 2.0 structures
=> Changes to hazard statement domain topics

specification/langRef/base/desc.dita, specification/langRef/base/dl.dita, specification/langRef/base/linklist.dita, specification/langRef/base/linkpool.dita
Moving normative statements into "Processing expectations" section
=> Moving normative statements into "Processing expectations" section

specification/common/conref-attribute.dita, specification/langRef/base/link.dita, specification/langRef/base/linkinfo.dita, specification/langRef/base/linklist.dita, specification/langRef/base/linkpool.dita, specification/langRef/base/linktext.dita, specification/langRef/base/related-links.dita, specification/langRef/containers/related-links-elements.dita, specification/langRef/related-links-elements.ditamap
Implementing new topic structure
=> Restructuring related-links element topics

specification/langRef/base-elements.ditamap, specification/langRef/base/audio.dita, specification/langRef/base/fallback.dita, specification/langRef/base/media-autoplay.dita, specification/langRef/base/media-controls.dita, specification/langRef/base/media-loop.dita, specification/langRef/base/media-muted.dita, specification/langRef/base/media-source.dita, specification/langRef/base/media-track.dita, specification/langRef/base/object.dita, specification/langRef/base/video-poster.dita, specification/langRef/base/video.dita, specification/langRef/body-elements.ditamap, specification/langRef/containers/multimedia-domain.dita, specification/langRef/multimedia-domain.ditamap, specification/langRef/quick-reference/base-elements-a-to-z.dita
Integrating topics and map; changes to object
=> Multimedia domain

specification/langRef/base/alt.dita, specification/langRef/base/b.dita, specification/langRef/base/body.dita, specification/langRef/base/dd.dita, specification/langRef/base/desc.dita, specification/langRef/base/dl.dita, specification/langRef/base/dlentry.dita, specification/langRef/base/dlhead.dita, specification/langRef/base/dt.dita, specification/langRef/base/fig.dita, specification/langRef/base/i.dita, specification/langRef/base/image.dita, specification/langRef/base/keydef.dita, specification/langRef/base/li.dita, specification/langRef/base/ol.dita, specification/langRef/base/ul.dita
Signed-off-by: Robert D Anderson <robander@us.ibm.com>
Incorporates changes discussed during a call with Kris and Carlos about topics relevant to both DITA 2.0 and LwDITA (primarily rewording short descriptions to use natural language and updating examples).
=> Updates to LwDITA elements during call with Kris and Carlos

specification/common/conref-file.dita, specification/langRef/base/shortdesc.dita
Reworked shortdesc topic per decisions made on the spec editing call on 14 June 2018
=> Reworking shortdesc topic

specification/langRef/base/topicref.dita
Updates to topicref topic based on 14 June 2018 spec editing call
=> Updates to topicref topic

specification/langRef/base/shortdesc.dita
Removing one paragraph about shortdesc being in both topic and map.
=> Changes made during spec call 21 June 2018

specification/langRef/base/map.dita, specification/langRef/base/xref.dita
Reworked <map> and <topicref> topics; added draft comments
=> Reworked topics; added draft comments

specification/common/conref-short-descriptions.dita, specification/dita-2.0-specification.ditamap, specification/langRef/base/navtitle.dita
Done as part of examples requested by the TC
=> Updates to navtitle topic

specification/common/conref-short-descriptions.dita, specification/langRef/base/cite.dita, specification/langRef/base/div.dita, specification/langRef/base/dl.dita, specification/langRef/base/draft-comment.dita, specification/langRef/base/figgroup.dita, specification/langRef/base/harvested-content-base.dita, specification/langRef/base/keyword.dita, specification/langRef/base/lines.dita, specification/langRef/base/longdescref.dita, specification/langRef/base/longquoteref.dita, specification/langRef/base/lq.dita, specification/langRef/base/p.dita, specification/langRef/base/pre.dita, specification/langRef/base/q.dita, specification/langRef/base/sl.dita, specification/langRef/base/sli.dita
Applying phase 2 edits to body elements
=> Phase 2 edits to body elements

specification/common/conref-short-descriptions.dita, specification/langRef/base/harvested-content-base.dita, specification/langRef/base/pre.dita, specification/langRef/base/prolog.dita, specification/langRef/base/section.dita, specification/langRef/base/shortdesc.dita, specification/langRef/base/simpletable.dita, specification/langRef/base/stentry.dita, specification/langRef/base/sub.dita, specification/langRef/base/sup.dita, specification/langRef/base/title.dita, specification/langRef/base/topic.dita
Call with Robert Anderson and Tom Magliery
=> Sec editing updates, 12 July 2018

specification/common/conref-attribute.dita, specification/langRef/base/data.dita, specification/langRef/base/desc.dita, specification/langRef/base/i.dita, specification/langRef/base/pre.dita, specification/langRef/base/reltable.dita, specification/langRef/base/shortdesc.dita, specification/langRef/base/title.dita
Adding missing shortdesc, removing redundant normative statement, etc.
=> Small edits

specification/common/conref-attribute.dita, specification/langRef/base/harvested-content-base.dita, specification/langRef/base/mapref.dita, specification/langRef/base/topicgroup.dita, specification/langRef/base/topichead.dita
=> Refactored map-group elements topics

specification/common/conref-short-descriptions.dita, specification/langRef/base/data.dita, specification/langRef/base/desc.dita, specification/langRef/base/draft-comment.dita, specification/langRef/base/harvested-content-base.dita, specification/langRef/base/map.dita, specification/langRef/base/note.dita, specification/langRef/base/section.dita, specification/langRef/base/shortdesc.dita, specification/langRef/base/topicmeta.dita, specification/langRef/base/xref.dita
* Changes to topics made during editorial call
* Changes to topics agreed upon during editorial call
=> Changes from editorial call, 30 August 2018

specification/langRef/base/body.dita, specification/langRef/base/li.dita, specification/langRef/base/ol.dita, specification/langRef/base/ph.dita, specification/langRef/base/prolog.dita, specification/langRef/base/simpletable.dita, specification/langRef/base/ul.dita
Edits performed by Tom Magliery on assigned element reference topics
=> Edits from Tom Magliery

specification/langRef/base/ddhd.dita, specification/langRef/base/dthd.dita
Correct errors introduced by editing before DITAweb review
=> Correct broken cross references

specification/archSpec/base/ditamap-elements.dita, specification/archSpec/base/dtd-coding-overview.dita, specification/archSpec/base/example-contraints-correct-machinery-task-constraint.dita, specification/archSpec/base/example-multiple-ditavalref.dita, specification/archSpec/base/examples-constraints.ditamap, specification/archSpec/base/keyScopes.dita, specification/archSpec/base/specialization-class-attribute.dita, specification/dita-2.0-specification-subjectScheme.ditamap, specification/introduction/formatting-conventions-in-errata.dita, specification/langRef/attributes/universalAttributes.dita, specification/langRef/base/created.dita, specification/langRef/base/image.dita, specification/langRef/base/index-base.dita, specification/langRef/base/required-cleanup.dita, specification/langRef/base/table.dita, specification/langRef/base/ux-window.dita, specification/langRef/containers/technical-content-elements.dita, specification/langRef/containers/troubleshooting-elements.dita, specification/resources/oasis-errata-cover.dita
Removing revision marking for 1.3 errata releases
=> Removing errata revision marking

specification/common/conref-attribute.dita, specification/common/conref-short-descriptions.dita, specification/dita-2.0-draft-pdf.ditamap, specification/langRef/base/alt.dita, specification/langRef/base/data.dita, specification/langRef/base/desc.dita, specification/langRef/base/dl.dita, specification/langRef/base/fn.dita, specification/langRef/base/i.dita, specification/langRef/base/image.dita, specification/langRef/base/navtitle.dita, specification/langRef/base/ol.dita, specification/langRef/base/ph.dita, specification/langRef/base/pre.dita, specification/langRef/base/prolog.dita, specification/langRef/base/title.dita, specification/langRef/base/u.dita, specification/langRef/base/ul.dita, specification/langRef/base/xref.dita, specification/langRef/lwdita-elements.ditamap
Updates made to resolve comments from the October 2018 review
=> DITAweb review #2

specification/common/conref-short-descriptions.dita
Updates to short descriptions, response to Oct 2018 DITAweb review
=> Updates based on 28 Jan 2019 editorial call

specification/common/conref-processing-expectations.dita, specification/common/key-definitions-library-topics.ditamap, specification/langRef/base/data.dita, specification/langRef/base/desc.dita, specification/langRef/base/fn.dita, specification/langRef/base/image.dita, specification/langRef/base/keydef.dita, specification/langRef/base/map.dita, specification/langRef/base/pre.dita, specification/langRef/base/section.dita, specification/langRef/base/shortdesc.dita
Moving "Processing expectations" content for intersection topics into a reuse topic
=> Moving "Processing expectations" content

specification/common/conref-processing-expectations.dita, specification/common/conref-usage-information.dita, specification/common/key-definitions-library-topics.ditamap, specification/langRef/base/data.dita, specification/langRef/base/desc.dita, specification/langRef/base/fn.dita, specification/langRef/base/keydef.dita
Moving usage info to common topic
=> Usage information

specification/archSpec/base/branch-filtering.ditamap, specification/archSpec/base/conditonal-processing.ditamap, specification/archSpec/base/conref.ditamap, specification/archSpec/base/processing.ditamap, specification/conformance/conformance.dita, specification/dita-2.0-draft-pdf.ditamap, specification/langRef/base/topichead.dita
Add @id for topics referenced in the Conformance topic
=> Add @id for topics referenced in the Conformance topic

specification/langRef/base/audio.dita, specification/langRef/base/media-autoplay.dita, specification/langRef/base/media-controls.dita, specification/langRef/base/media-loop.dita, specification/langRef/base/media-muted.dita, specification/langRef/base/media-source.dita, specification/langRef/base/media-track.dita, specification/langRef/base/video-poster.dita, specification/langRef/base/video.dita
=> Revert "Multimedia"
